fti_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: fti_user
      password: fti_password
      port: 5432
      dbname: fti_db
      schema: public
      threads: 4